#version 430 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D imgOutput;

uniform vec2 pos;
uniform vec2 dir;
uniform vec2 plane;

void main()
{
    float cameraX = float((gl_GlobalInvocationID.x * 2.0 / gl_WorkGroupSize.x) - 1.0); //x-coordinate in camera space

    //calculate ray position and direction
    vec2 rayDir = dir + (plane * cameraX);
    ivec2 mapPos = ivec2(pos);
}